front_practica_2/routes/route_transaccion.py
from .route_familia import *
from .route_generador import G_URL

router_transaccion = Blueprint('router_transaccion',__name__)

T_URL = f'{BASE_URL}/transaccion'

# TABLE TRANSACCIÓN ========================================================================

@router_transaccion.route('/transaccion/table')
def table_transaccion():
    response = requests.get(f'{T_URL}/all')
    attributes = requests.get(f'{T_URL}/attributes').json()['data']
    transacciones = response.json()['data']
    i = 1
    for transaccion in transacciones:
        transaccion['numero'] = i
        headers = {'Content-Type':'application/json'}
        familia = requests.get(f'{F_URL}/get/{transaccion['familiaId']}',headers=headers).json()['data']
        transaccion['apellidosFamilia'] = familia['apellidosRepresentantes']
        generador = requests.get(f'{G_URL}/get/{transaccion['generadorId']}',headers=headers).json()['data']
        transaccion['generadorModelo'] = generador['modelo']
        i += 1
    return render_template('transaccion/table_transaccion.html',transacciones=transacciones,attributes=attributes)

# BÚSQUEDA Y ORDENACIÓN ========================================================================

@router_transaccion.route('/transaccion/search/<attribute>/<value>')
def transaccion_search(attribute,value):
    response = requests.get(f'{T_URL}/search/{attribute}/{value}')
    if response.status_code != 200:
        flash(response.json()['data'],category=response.json()['status'])
        return redirect('/transaccion/table')
    attributes = requests.get(f'{T_URL}/attributes').json()['data']
    transacciones = response.json()['data']
    for i in range(0,len(transacciones)): 
        transacciones[i]['numero'] = i+1
        transacciones[i]['apellidosFamilia'] = requests.get(f'{F_URL}/get/{transacciones[i]['familiaId']}').json()['data']['apellidosRepresentantes']
        transacciones[i]['generadorModelo'] = requests.get(f'{G_URL}/get/{transacciones[i]['generadorId']}').json()['data']['modelo']

    return render_template('transaccion/table_transaccion.html',transacciones=transacciones,attributes=attributes)

@router_transaccion.route('/transaccion/sort/<attribute>/<orden>/<typesort>')
def transaccion_sort(attribute,orden,typesort):
    response = requests.get(f'{T_URL}/sort/{attribute}/{orden}/{typesort}')
    attributes = requests.get(f'{T_URL}/attributes').json()['data']
    transacciones = response.json()['data']
    for i in range(0,len(transacciones)): 
        transacciones[i]['numero'] = i+1
        transacciones[i]['apellidosFamilia'] = requests.get(f'{F_URL}/get/{transacciones[i]['familiaId']}').json()['data']['apellidosRepresentantes']
        transacciones[i]['generadorModelo'] = requests.get(f'{G_URL}/get/{transacciones[i]['generadorId']}').json()['data']['modelo']
    return render_template('transaccion/table_transaccion.html',transacciones=transacciones,attributes=attributes)

# TRANSACCION SAVE ========================================================================

@router_transaccion.route('/transaccion/save')
def save_transaccion():
    response = requests.get(f'{F_URL}/all')
    familias = response.json()['data']
    response = requests.get(f'{G_URL}/all')
    generadores = response.json()['data']
    usosGenerador =  requests.get(f'{T_URL}/enumerations').json()['data']
    context={
        'familias' : familias,
        'generadores' : generadores,
        'usosGenerador' : usosGenerador
    }
    return render_template('/transaccion/save_transaccion.html',context=context)
    
@router_transaccion.route('/transaccion/save/send',methods=['POST'])
def save_transaccion_send():
    data = request.form.to_dict()
    headers = {'Content-Type':'application/json'}
    response = requests.post(f'{T_URL}/save/',json=data,headers=headers)
    msg = response.json()
    key = ['info','info'] if response.status_code == 201 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
    return redirect('/transaccion/table')

# TRANSACCION UPDATE ========================================================================

@router_transaccion.route('/transaccion/update/<int:id>')
def update_transaccion(id):
    response = requests.get(f'{T_URL}/get/{id}')
    transaccion = response.json()['data']
    response = requests.get(f'{G_URL}/all')
    generadores = response.json()['data']
    response = requests.get(f'{F_URL}/all')
    familias = response.json()['data']
    enums = requests.get(f'{T_URL}/enumerations').json()['data']
    context = {'familias': familias, 'generadores': generadores, 'enums' : enums}
    return render_template('transaccion/update_transaccion.html',transaccion=transaccion,context=context)

@router_transaccion.route('/transaccion/update/send',methods=['POST'])
def update_transaccion_send():
    json = request.form.to_dict()
    headers = {'Content-Type':'application/json'}
    response = requests.post(f'{T_URL}/update',json=json,headers=headers)
    msg = response.json()
    key = ['info','info'] if response.status_code == 200 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
    return redirect('/transaccion/table')

# TRANSACCION DELETE ========================================================================

@router_transaccion.route('/transaccion/delete/<int:id>')
def delete_transaccion(id):
    response = requests.get(f'{T_URL}/get/{id}')
    transaccion = response.json()['data']
    return render_template('transaccion/delete_transaccion.html',transaccion=transaccion)

@router_transaccion.route('/transaccion/delete/send',methods=['POST'])
def delete_transaccion_send():
    response = requests.delete(f'{T_URL}/delete/{request.form['id']}')
    msg = response.json()
    key = ['info','info'] if response.status_code == 200 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
    return redirect('/transaccion/table')

front_practica_2/templates/transaccion/delete_transaccion.html
{% extends 'transaccion/transaccion_base.html' %}
{% block title %}Eliminar transaccion{% endblock %}
{% block extra_routes %}
  <a href="#"> - </a><a href="/transaccion/delete/{{transaccion.id}}">Eliminar {{transaccion.id}}</a>
{% endblock %}
{% block content %}
<div class="card">
  <div class="card-header">
      <h4 class="card-title">Eliminar datos de transaccion {{transaccion.id}}</h4>
  </div>

  <div class="card-block">
      <div class="card-body">
        <h3>¿Está seguro que quiere perder para siempre los siguientes datos?</h3>
        <div class="card-text">
          <ul>
            <li><strong>{{transaccion.id}}</strong></li>
            <li><strong>Familia: </strong>{{transaccion.familiaId}}</li>
            <li><strong>Generador: </strong>{{transaccion.generadorId}}</li>
            <li><strong>Uso del Generador: </strong>{{transaccion.usoGenerador}}</li>
          </ul> 
          <form action="/transaccion/delete/send" method="post">
            <input type="number" name="id" value="{{transaccion.id}}" readonly hidden>
            <a href="/transaccion/table">
              <button type="button" class="btn btn-success btn-min-width mr-1 mb-1"><i class="la la-chevron-left"></i>Volver</button>
            </a>
            <button type="submit" class="btn btn-danger btn-min-width mr-1 mb-1"><i class="la la-trash"></i>Eliminar</button>
          </form>
          </form>
        </div>         
      </div>
  </div>
</div>
  
{% endblock %}

front_practica_2/templates/transaccion/save_transaccion.html
{% extends 'transaccion/transaccion_base.html' %}
{% block title %}Guardar transaccion{% endblock %}
{% block extra_routes %}
  <a href="#"> - </a><a href="/transaccion/save">Guardar</a>
{% endblock %}
{% block content %}
<div class="card">
  <div class="card-header">
    <h4 class="card-title">GUARDAR TRANSACCION</h4>
  </div>
  <div class="card-block">
    <div class="card-body">

      <a href="/transaccion/table">
        <button type="button" class="btn btn-icon btn-danger mr-1">
          <i class="la la-arrow-left"></i> <strong>Tabla de transacciones</strong>
        </button>
      </a>

      <form action="/transaccion/save/send" method="post">

        <h5 class="mt-2"><label for="numeroTransaccion">Numero único de Transacción</label></h5>
        <fieldset class="form-group">
            <input required type="text" class="form-control" id="numeroTransaccion" name="numeroTransaccion" placeholder="ej. 000T56">
        </fieldset>
        
        <h5 class="mt-2"><label for="familiaId">Familia</label></h5>
        <fieldset class="form-group">
            <select class="form-control" name="familiaId" id="familiaId" required>
              {% for familia in context.familias %}
                <option value="{{familia.id}}">{{familia.apellidosRepresentantes}}</option>
              {% endfor %}
            </select>
        </fieldset>
        
        <h5 class="mt-2"><label for="generadorId">Generador</label></h5>
        <fieldset class="form-group">
          <select class="form-control" name="generadorId" id="generadorId" required>
            {% for generador in context.generadores %}
              <option value="{{generador.id}}">{{generador.modelo}}</option>
            {% endfor %}
          </select>
        </fieldset>

        <h5 class="mt-2"><label for="usoGenerador">Uso del Generador</label></h5>
        <fieldset class="form-group">
          <select class="form-control" name="usoGenerador" id="usoGenerador" required>
            {% for uso in context.usosGenerador %}
              <option value="{{uso}}">{{uso}}</option>
            {% endfor %}
          </select>
        </fieldset>

        <h5 class="mt-2"><label for="ingresosMensuales">Cantidad de Generadores comprados por la familia</label></h5>
        <fieldset class="form-group">
            <input required min="1" type="number" step="1" class="form-control" id="nombres" name="cantidadGeneradores">
        </fieldset>

        <button type="submit" class="btn mb-1 btn-primary btn-lg btn-block">Guardar Transaccion</button>
      </form>

    </div>
  </div>
</div>
{% endblock %}

front_practica_2/templates/transaccion/table_transaccion.html
{% extends 'transaccion/transaccion_base.html' %}
{% block title %}Tabla de transacciones{% endblock %}

{% block static_content %}
  <link rel="stylesheet" href="{{ url_for('static',filename='assets/css/search.css') }}">
{% endblock %}

{% block content %}

<div class="card">
  <div class="card-header">
      <h4 class="card-title">Transacciones Registradas</h4>
  </div>
    {% with messages = get_flashed_messages(with_categories=True)  %}
      {% if messages %}
        {% for message in messages %}
          {% if message[0] == 'info' %}
          <p class="card-subtitle" style="color:#11fc2d"> <i class="la la-check-circle-o"></i> {{ message[1] }}</p>
          {% else %}     
            <p class="card-subtitle" style="color: #fc1111;"> <i class="la la-remove"></i> {{ message[1] }}</p>
          {% endif %}               
        {% endfor %}         
      {% endif %}
    {% endwith %}
  <div class="card-block">
      <div class="card-body">
        <a href="/transaccion/save">
          <button type="button" class="btn btn-dark btn-min-width mr-1 mb-1">
            <i class="la la-plus"></i>
          </button>
        </a>
        
        <a id="searchRequest" href="/transaccion/table" hidden></a>
          <a id="sortRequest" href="/transaccion/table" hidden></a>
        

          <div class="btn-group mr-1 mb-1">
            <button type="button" class="btn btn-info" onclick="searchUtility('transaccion')"><i class="la la-search"></i></button>
            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            </button>
            <div class="dropdown-menu">
                {% for attribute in attributes %}
                  <p class="p-option" value="{{ attribute }}" onclick="buildSearchUrl('transaccion','{{ attribute }}')">{{ attribute }}</p>
                {% endfor %}
            </div>
          </div>
          <input type="text" id="inputS"><br>

          <div class="btn-group mr-1 mb-1">
              <button type="button" class="btn btn-info" onclick="sortUtility('transaccion','1')"><i class="la la-sort-amount-asc"></i></button>
              <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              </button>
              <div class="dropdown-menu">
                  {% for attribute in attributes %}
                    <p class="p-option" value="{{ attribute }}" onclick="buildSortUrl('transaccion','{{ attribute }}')">{{ attribute }}</p>
                  {% endfor %}
              </div>
          </div>

          <div class="btn-group mr-1 mb-1">
            <button type="button" class="btn btn-info" onclick="sortUtility('transaccion','0')"><i class="la la-sort-amount-desc"></i></button>
            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            </button>
            <div class="dropdown-menu">
                {% for attribute in attributes %}
                  <p class="p-option" value="{{ attribute }}" onclick="buildSortUrl('transaccion','{{ attribute }}')">{{ attribute }}</p>
                {% endfor %}
            </div>
        </div>

        <select name="selection" id="inputSrt">
          <option value="0" onclick="tipeSort('0')">QUICK_SORT</option>
          <option value="1" onclick="tipeSort('1')">MERGE_SORT</option>
          <option value="2" onclick="tipeSort('2')">SHELL_SORT</option>
        </select>

        <table class="table">
          <thead class="thead-dark">
            <th>Nro</th>
            <th>Numero Transacción</th>
            <th>Familia</th>
            <th>Generador</th>
            <th>Uso del generador</th>
            <th>Cantidad Generadores</th>
            <th>Precio Final</th>
            <th>Acción</th>
          </thead>
          <tbody>
            {% for transaccion in transacciones %}
              <tr>
                <td>{{ transaccion.numero }}</td>
                <td>{{ transaccion.numeroTransaccion }}</td>
                <td>{{ transaccion.apellidosFamilia }}</td>
                <td>{{ transaccion.generadorModelo }}</td>
                <td>{{ transaccion.usoGenerador}}</td>
                <td>{{ transaccion.cantidadGeneradores }}</td>
                <td>{{ transaccion.precioFinal }}</td>
                <td>
                  <a href="{{ url_for('router_transaccion.update_transaccion',id=transaccion.id) }}" ><i class="la la-pencil"></i></a>
                  <a href="{{ url_for('router_transaccion.delete_transaccion',id=transaccion.id) }}" ><i class="la la-trash"></i></a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>      
      </div>
  </div>
</div>

<script src="{{ url_for('static',filename='js/sortSearchScript.js') }}"></script>
  
{% endblock %}

front_practica_2/templates/transaccion/transaccion_base.html
{% extends 'base.html' %}
{% block main_menu_content %}
<div class="main-menu-content">
  <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
    <li class="nav-item"><a href="/"><i class="ft-home"></i><span class="menu-title"
          data-i18n="">Inicio</span></a>
    </li>
    <li class="nav-item"><a href="/familia/table"><i class="la la-group"></i><span class="menu-title"
          data-i18n="">Familias</span></a>
    </li>
    <li class="nav-item"><a href="/generador/table"><i class="la la-lightbulb-o"></i><span class="menu-title"
      data-i18n="">Generadores</span></a>
    </li>
    <li class="active"><a href="/transaccion/table"><i class="la la-exchange"></i><span class="menu-title"
      data-i18n="">Transacciones</span></a>
    </li>
    <li class="nav-item"><a href="/historial/table"><i class="la la-history"></i><span class="menu-title"
      data-i18n="">Historial Acciones</span></a>
    </li>
  </ul>
</div>
<div class="navigation-background"></div>
</div>
{% endblock %}

{% block app_content %}
<div class="app-content content">
  <div class="content-wrapper">
    <div class="content-wrapper-before"></div>
    <div class="content-header row">
      <div class="content-header-left col-md-4 col-12 mb-2">
        <h3 class="content-header-title">TRANSACCIONES</h3>
      </div>
      <div class="content-header-right col-md-8 col-12">
        <div class="breadcrumbs-top float-md-right">
          <div class="breadcrumb-wrapper mr-1">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="/">Home</a><a href="#"> - </a><a href="/transaccion/table">Transacciones</a>{% block extra_routes %} {% endblock %}
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

front_practica_2/templates/transaccion/update_transaccion.html
{% extends 'transaccion/transaccion_base.html' %}
{% block title %}Actualizar datos del transaccion{% endblock %}
{% block extra_routes %}
  <a href="#"> - </a><a href="/update/transaccion/{{transaccion.id}}">Editar {{transaccion.id}}</a>
{% endblock %}
{% block content %}
<div class="card">
  <div class="card-header">
    <h4 class="card-title">ACTUALIZAR TRANSACCION</h4>
  </div>
  <div class="card-block">
    <div class="card-body">

      <a href="/transaccion/table">
        <button type="button" class="btn btn-icon btn-danger mr-1">
          <i class="la la-arrow-left"></i> <strong>Volver</strong>
        </button>
      </a>

      <form action="/transaccion/update/send" method="post">
        <input hidden type="number" value="{{transaccion.id}}" name="id">

        <h5 class="mt-2"><label for="numeroTransaccion">Numero único de Transacción</label></h5>
        <fieldset class="form-group">
            <input required type="text" class="form-control" id="numeroTransaccion" name="numeroTransaccion" value="{{ transaccion.numeroTransaccion }}">
        </fieldset>

        <h5 class="mt-2"><label for="familiaId">Familia</label></h5>
        <fieldset class="form-group">
            <select class="form-control" name="familiaId" id="familiaId" required>
              {% for familia in context.familias %}
                <option
                {% if transaccion.familiaId == familia.id %}
                  selected
                {% endif %}
                value="{{familia.id}}">{{familia.apellidosRepresentantes}}</option>
              {% endfor %}
            </select>
        </fieldset>
        
        <h5 class="mt-2"><label for="generadorId">Generador</label></h5>
        <fieldset class="form-group">
          <select class="form-control" name="generadorId" id="generadorId" required>
            {% for generador in context.generadores %}
              <option
              {% if transaccion.generadorId == generador.id %}
                selected
              {% endif %}
              value="{{generador.id}}">{{generador.modelo}}</option>
            {% endfor %}
          </select>
        </fieldset>

        <h5 class="mt-2"><label for="usoGenerador">Uso del Generador</label></h5>
        <fieldset class="form-group">
          <select class="form-control" name="usoGenerador" id="usoGenerador" required>
            {% for uso in context.enums %}
              <option
              {% if uso == transaccion.usoGenerador %}
                selected
              {% endif %}
              value="{{uso}}">{{uso}}</option>
            {% endfor %}
          </select>
        </fieldset>

        <h5 class="mt-2"><label for="ingresosMensuales">Cantidad de Generadores comprados por la familia</label></h5>
        <fieldset class="form-group">
            <input required value="{{ transaccion.cantidadGeneradores }}" min="1" type="number" step="1" class="form-control" id="nombres" name="cantidadGeneradores">
        </fieldset>

        <button type="submit" class="btn mb-1 btn-primary btn-lg btn-block">Actualizar Transaccion</button>
      </form>

    </div>
  </div>
</div>
  
{% endblock %}