front_practica_2/routes/route_familia.py
from flask import Blueprint, redirect, render_template, request, flash
import requests

router_familia = Blueprint('router_familia',__name__)

@router_familia.route('/')
def home():
    return render_template('index.html')

BASE_URL = 'http://localhost:8080/api'

F_URL = f'{BASE_URL}/familia'

# TABLE FAMILIA =============================================================================================

@router_familia.route('/familia/table')
def table_familia():
    response = requests.get(f'{F_URL}/all')
    attributes = requests.get(f'{F_URL}/attributes').json()['data']
    familias = response.json()['data']
    for i in range(0,len(familias)): 
        familias[i]['numero'] = i+1
    return render_template('familia/table_familia.html',familias=familias,attributes=attributes)


# BÚSQUEDA Y ORDENACIÓN ====================================================================================

@router_familia.route('/familia/search/<attribute>/<value>')
def search(attribute,value):
    response = requests.get(f'{F_URL}/search/{attribute}/{value}')
    attributes = requests.get(f'{F_URL}/attributes').json()['data']
    familias = response.json()['data']
    for i in range(0,len(familias)): 
        familias[i]['numero'] = i+1
    return render_template('familia/table_familia.html',familias=familias,attributes=attributes)

@router_familia.route('/familia/sort/<attribute>/<orden>/<typesort>')
def sort(attribute,orden,typesort):
    response = requests.get(f'{F_URL}/sort/{attribute}/{orden}/{typesort}')
    attributes = requests.get(f'{F_URL}/attributes').json()['data']
    familias = response.json()['data']
    for i in range(0,len(familias)): 
        familias[i]['numero'] = i+1
    return render_template('familia/table_familia.html',familias=familias,attributes=attributes)


# SAVE FAMILIA ============================================================================================

@router_familia.route('/familia/save')
def save_familia():
    response = requests.get(f'{F_URL}/enumerations')
    return render_template('familia/save_familia.html',enumeracion=response.json()['data'])

@router_familia.route('/familia/save/send', methods=['POST'])
def save_familia_send():
    headers = {'Content-Type':'application/json'}
    data = request.form.to_dict()
    response = requests.post(f'{F_URL}/save',json=data,headers=headers)
    msg = response.json()
    key = ['info','info'] if response.status_code == 201 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
    return redirect('/familia/table')
    
# FAMILIA UPDATE ========================================================================

@router_familia.route('/familia/update/<int:id>')
def update_familia(id):
    response = requests.get(f'{F_URL}/get/{id}')
    familia = response.json()['data']
    response = requests.get(f'{F_URL}/enumerations')
    print(response)
    enums = response.json()['data']
    
    return render_template('familia/update_familia.html',context={"familia": familia, "enums" : enums})

@router_familia.route('/familia/update/send',methods=['POST'])
def update_familia_send():
    data = request.form.to_dict()
    headers = {'Content-Type':'application/json'}
    response = requests.post(f'{F_URL}/update',json=data,headers=headers)
    msg = response.json()
    key = ['info','info'] if response.status_code == 200 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
        
    return redirect('/familia/table')

# DELETE FAMILIA ========================================================================

@router_familia.route('/delete/familia/<int:id>')
def delete_familia(id):
    response = requests.get(f'{F_URL}/get/{id}')
    familia = response.json()['data']
    return render_template('familia/delete_familia.html',familia=familia)

@router_familia.route('/delete/familia/send',methods=['POST'])
def delete_familia_send():
    response = requests.delete(f'{F_URL}/delete/{request.form['id']}')
    msg = response.json()
    key = ['info','info'] if response.status_code == 200 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
    return redirect('/familia/table')



# HISTORIAL DE ACCIONES ==============================================================================

H_URL = f'{BASE_URL}/historial'

@router_familia.route('/historial/table')
def table_historial():
    acciones = requests.get(f'{H_URL}/all').json()['data']
    attributes = requests.get(f'{H_URL}/attributes').json()['data']
    for i in range(0,len(acciones)):
        acciones[i]['numero'] = i+1
    return render_template('historial/table_historial.html',acciones=acciones,attributes=attributes)

# DELETE ACCION =================================================================================

@router_familia.route('/historial/delete/<id>')
def delete_historial(id):
    accion = requests.get(f'{H_URL}/get/{id}').json()['data']
    print(accion)
    return render_template('historial/delete_historial.html',accion=accion)

@router_familia.route('/historial/delete/send/<id>')
def delete_historial_send(id):
    response = requests.delete(f'{H_URL}/delete/{id}')
    msg = response.json()
    key = ['info','info'] if response.status_code == 200 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
    return redirect('/historial/table')

# BUSQUEDA Y ORDENACIÓN =================================================================

@router_familia.route('/historial/search/<attribute>/<value>')
def historial_search(attribute,value):
    response = requests.get(f'{H_URL}/search/{attribute}/{value}')
    attributes = requests.get(f'{H_URL}/attributes').json()['data']
    acciones = response.json()['data']
    for i in range(0,len(acciones)): 
        acciones[i]['numero'] = i+1
    return render_template('historial/table_historial.html',acciones=acciones,attributes=attributes)

@router_familia.route('/historial/sort/<attribute>/<orden>/<typesort>')
def historial_sort(attribute,orden,typesort):
    response = requests.get(f'{H_URL}/sort/{attribute}/{orden}/{typesort}')
    attributes = requests.get(f'{H_URL}/attributes').json()['data']
    acciones = response.json()['data']
    for i in range(0,len(acciones)): 
        acciones[i]['numero'] = i+1
    return render_template('historial/table_historial.html',acciones=acciones,attributes=attributes)


# Ay! bendita sea mi mama
# por haberme parido macho!
# Aaay, mama!

#🗣️🗣️🗣️🗣️🗣️🗣️🗣️

front_practica_2/routes/route_generador.py
from .route_familia import *

router_generador = Blueprint('router_generador',__name__)

G_URL = f'{BASE_URL}/generador'

# TABLE GENERADOR ================================================================================

@router_generador.route('/generador/table')
def table_generador():
    response = requests.get(f'{G_URL}/all')
    attributes = requests.get(f'{G_URL}/attributes').json()['data']
    generadores = response.json()['data']
    for i in range(0,len(generadores)):
        generadores[i]['numero'] = i+1
    return render_template('generador/table_generador.html',generadores=generadores,attributes=attributes)


# BÚSQUEDA Y ORDENACIÓN ========================================================================

@router_familia.route('/generador/search/<attribute>/<value>')
def generador_search(attribute,value):
    response = requests.get(f'{G_URL}/search/{attribute}/{value}')
    attributes = requests.get(f'{G_URL}/attributes').json()['data']
    generadores = response.json()['data']
    for i in range(0,len(generadores)): 
        generadores[i]['numero'] = i+1
    return render_template('generador/table_generador.html',generadores=generadores,attributes=attributes)

@router_familia.route('/generador/sort/<attribute>/<orden>/<typesort>')
def generador_sort(attribute,orden,typesort):
    response = requests.get(f'{G_URL}/sort/{attribute}/{orden}/{typesort}')
    attributes = requests.get(f'{G_URL}/attributes').json()['data']
    generadores = response.json()['data']
    for i in range(0,len(generadores)): 
        generadores[i]['numero'] = i+1
    return render_template('generador/table_generador.html',generadores=generadores,attributes=attributes)

# SAVE GENERADOR =================================================================================

@router_generador.route('/generador/save')
def save_generador():
    return render_template('/generador/save_generador.html')
    
@router_generador.route('/generador/save/send',methods=['POST'])
def save_generador_send():
    data = request.form.to_dict()
    headers = {'Content-Type':'application/json'}
    response = requests.post(f'{G_URL}/save/',json=data,headers=headers)
    msg = response.json()
    key = ['info','info'] if response.status_code == 201 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
    return redirect('/generador/table')

# UPDATE GENERADOR ==============================================================================

@router_generador.route('/generador/update/<int:id>')
def update_generador(id):
    response = requests.get(f'{G_URL}/get/{id}')
    generador = response.json()['data']
    return render_template('generador/update_generador.html',generador=generador)

@router_generador.route('/generador/update/send',methods=['POST'])
def update_generador_send():
    json = request.form.to_dict()
    headers = {'Content-Type':'application/json'}
    response = requests.post(f'{G_URL}/update',json=json,headers=headers)
    msg = response.json()
    key = ['info','info'] if response.status_code == 200 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
    return redirect('/generador/table')

# DELETE GENERADOR =============================================================================

@router_generador.route('/generador/delete/<int:id>')
def delete_generador(id):
    response = requests.get(f'{G_URL}/get/{id}')
    generador = response.json()['data']
    return render_template('generador/delete_generador.html',generador=generador)

@router_generador.route('/generador/delete/send',methods=['POST'])
def delete_generador_send():
    response = requests.delete(f'{G_URL}/delete/{request.form['id']}')
    msg = response.json()
    key = ['info','info'] if response.status_code == 200 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
    return redirect('/generador/table')

front_practica_2/routes/route_transaccion.py
from .route_familia import *
from .route_generador import G_URL

router_transaccion = Blueprint('router_transaccion',__name__)

T_URL = f'{BASE_URL}/transaccion'

# TABLE TRANSACCIÓN ========================================================================

@router_transaccion.route('/transaccion/table')
def table_transaccion():
    response = requests.get(f'{T_URL}/all')
    attributes = requests.get(f'{T_URL}/attributes').json()['data']
    transacciones = response.json()['data']
    i = 1
    for transaccion in transacciones:
        transaccion['numero'] = i
        headers = {'Content-Type':'application/json'}
        familia = requests.get(f'{F_URL}/get/{transaccion['familiaId']}',headers=headers).json()['data']
        transaccion['apellidosFamilia'] = familia['apellidosRepresentantes']
        generador = requests.get(f'{G_URL}/get/{transaccion['generadorId']}',headers=headers).json()['data']
        transaccion['generadorModelo'] = generador['modelo']
        i += 1
    return render_template('transaccion/table_transaccion.html',transacciones=transacciones,attributes=attributes)

# BÚSQUEDA Y ORDENACIÓN ========================================================================

@router_transaccion.route('/transaccion/search/<attribute>/<value>')
def transaccion_search(attribute,value):
    response = requests.get(f'{T_URL}/search/{attribute}/{value}')
    if response.status_code != 200:
        flash(response.json()['data'],category=response.json()['status'])
        return redirect('/transaccion/table')
    attributes = requests.get(f'{T_URL}/attributes').json()['data']
    transacciones = response.json()['data']
    for i in range(0,len(transacciones)): 
        transacciones[i]['numero'] = i+1
        transacciones[i]['apellidosFamilia'] = requests.get(f'{F_URL}/get/{transacciones[i]['familiaId']}').json()['data']['apellidosRepresentantes']
        transacciones[i]['generadorModelo'] = requests.get(f'{G_URL}/get/{transacciones[i]['generadorId']}').json()['data']['modelo']

    return render_template('transaccion/table_transaccion.html',transacciones=transacciones,attributes=attributes)

@router_transaccion.route('/transaccion/sort/<attribute>/<orden>/<typesort>')
def transaccion_sort(attribute,orden,typesort):
    response = requests.get(f'{T_URL}/sort/{attribute}/{orden}/{typesort}')
    attributes = requests.get(f'{T_URL}/attributes').json()['data']
    transacciones = response.json()['data']
    for i in range(0,len(transacciones)): 
        transacciones[i]['numero'] = i+1
        transacciones[i]['apellidosFamilia'] = requests.get(f'{F_URL}/get/{transacciones[i]['familiaId']}').json()['data']['apellidosRepresentantes']
        transacciones[i]['generadorModelo'] = requests.get(f'{G_URL}/get/{transacciones[i]['generadorId']}').json()['data']['modelo']
    return render_template('transaccion/table_transaccion.html',transacciones=transacciones,attributes=attributes)

# TRANSACCION SAVE ========================================================================

@router_transaccion.route('/transaccion/save')
def save_transaccion():
    response = requests.get(f'{F_URL}/all')
    familias = response.json()['data']
    response = requests.get(f'{G_URL}/all')
    generadores = response.json()['data']
    usosGenerador =  requests.get(f'{T_URL}/enumerations').json()['data']
    context={
        'familias' : familias,
        'generadores' : generadores,
        'usosGenerador' : usosGenerador
    }
    return render_template('/transaccion/save_transaccion.html',context=context)
    
@router_transaccion.route('/transaccion/save/send',methods=['POST'])
def save_transaccion_send():
    data = request.form.to_dict()
    headers = {'Content-Type':'application/json'}
    response = requests.post(f'{T_URL}/save/',json=data,headers=headers)
    msg = response.json()
    key = ['info','info'] if response.status_code == 201 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
    return redirect('/transaccion/table')

# TRANSACCION UPDATE ========================================================================

@router_transaccion.route('/transaccion/update/<int:id>')
def update_transaccion(id):
    response = requests.get(f'{T_URL}/get/{id}')
    transaccion = response.json()['data']
    response = requests.get(f'{G_URL}/all')
    generadores = response.json()['data']
    response = requests.get(f'{F_URL}/all')
    familias = response.json()['data']
    enums = requests.get(f'{T_URL}/enumerations').json()['data']
    context = {'familias': familias, 'generadores': generadores, 'enums' : enums}
    return render_template('transaccion/update_transaccion.html',transaccion=transaccion,context=context)

@router_transaccion.route('/transaccion/update/send',methods=['POST'])
def update_transaccion_send():
    json = request.form.to_dict()
    headers = {'Content-Type':'application/json'}
    response = requests.post(f'{T_URL}/update',json=json,headers=headers)
    msg = response.json()
    key = ['info','info'] if response.status_code == 200 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
    return redirect('/transaccion/table')

# TRANSACCION DELETE ========================================================================

@router_transaccion.route('/transaccion/delete/<int:id>')
def delete_transaccion(id):
    response = requests.get(f'{T_URL}/get/{id}')
    transaccion = response.json()['data']
    return render_template('transaccion/delete_transaccion.html',transaccion=transaccion)

@router_transaccion.route('/transaccion/delete/send',methods=['POST'])
def delete_transaccion_send():
    response = requests.delete(f'{T_URL}/delete/{request.form['id']}')
    msg = response.json()
    key = ['info','info'] if response.status_code == 200 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
    return redirect('/transaccion/table')

front_practica_2/templates/index.html
{% extends 'base.html' %}
{% block title %}Censos Loja{% endblock %}

{% block main_menu_content %}
<div class="main-menu-content">
  <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
    <li class="active"><a href="/"><i class="ft-home"></i><span class="menu-title"
          data-i18n="">Inicio</span></a>
    </li>
    <li class="nav-item"><a href="/familia/table"><i class="la la-group"></i><span class="menu-title"
          data-i18n="">Familias</span></a>
    </li>
    <li class="nav-item"><a href="/generador/table"><i class="la la-lightbulb-o"></i><span class="menu-title"
      data-i18n="">Generadores</span></a>
    </li>
    <li class="nav-item"><a href="/transaccion/table"><i class="la la-exchange"></i><span class="menu-title"
      data-i18n="">Transacciones</span></a>
    </li>
    <li class="nav-item"><a href="/historial/table"><i class="la la-history"></i><span class="menu-title"
      data-i18n="">Historial Acciones</span></a>
    </li>
  </ul>
</div>
<div class="navigation-background"></div>
</div> 
{% endblock %}


{% block app_content %}
<div class="app-content content">
  <div class="content-wrapper">
    <div class="content-wrapper-before"></div>
    <div class="content-header row">
      <div class="content-header-left col-md-4 col-12 mb-2">
        <h3 class="content-header-title">INICIO</h3>
      </div>
      <div class="content-header-right col-md-8 col-12">
        <div class="breadcrumbs-top float-md-right">
          <div class="breadcrumb-wrapper mr-1">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="/">Home</a>
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block content %}

<div class="card">
  <div class="card-header">
      <h2 class="card-title">Sistema de Estadísticas y Censos: Censos Loja</h2>
  </div>
  <div class="card-block">
      <div class="card-body">
        <p>En esta aplicación usted podrá visualizar y modificar datos relevantes sobre la adquisición de generadores de energía eléctrica por parte de las familias lojanas.</p>
        <div class="card-block">
          <div class="card-header">
            <h4 class="card-title">Acciones Rápidas</h4>
          </div> 
          <div class="card-body">
            <div class="form-group">
              <a href="{{ url_for('router_familia.save_familia') }}">
                <button type="button" class="btn btn-primary btn-min-width mr-1 mb-1"><i class="la la-plus"></i> Agregar Familia</button>
              </a>
              <a href="{{ url_for('router_generador.save_generador') }}">
                <button type="button" class="btn btn-primary btn-min-width mr-1 mb-1"><i class="la la-plus"></i> Agregar Generador</button>
              </a>
              <a href="{{ url_for('router_transaccion.save_transaccion') }}">
                <button type="button" class="btn btn-primary btn-min-width mr-1 mb-1"><i class="la la-plus"></i> Agregar Transacción</button>
              </a>
            </div> 
          </div>          
        </div>        
      </div>
  </div>
</div>

<div class="col-12 mt-3 mb-1">
  <h4 class="text-uppercase">Sobre el Sistema</h4>
  <p>A continuación se muestra una pequeña descripción de las funcionalidades del sistema.</p>
</div>

<div class="row match-height">
  <div class="col-lg-4 col-md-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Apartado de Familias</h4>
        <h6 class="card-subtitle text-muted">Tabla de datos con posibilidad de modificación</h6>
      </div>
      <img class="" src="https://imgs.search.brave.com/lLPJ0wjw3uvZW02pkZS9orsrrXCS-zSgcLoQl_wA2s0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWcu/ZnJlZXBpay5jb20v/Zm90by1ncmF0aXMv/ZmFtaWxpYS1mZWxp/ei1zZW50YWRvLXNv/ZmEtc2FsYS1lc3Rh/cl8yMy0yMTQ4NDU2/Mjc5LmpwZz9zZW10/PWFpc19oeWJyaWQ" alt="Card image cap">
      <div class="card-body">
        <p class="card-text">En esta sección usted podrá visualizar la lista actual de los datos de las familias registradas en el sistema</p>
        <a href="/familia/table" class="card-link">Ir a la sección</a>
      </div>
      <div class="card-footer border-top-blue-grey border-top-lighten-5 text-muted">
      </div>
    </div>
  </div>
  <div class="col-lg-4 col-md-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Apartado de Generadores</h4>
        <h6 class="card-subtitle text-muted">Tabla de datos con posibilidad de modificación</h6>
      </div>
      <img class="" src="https://imgs.search.brave.com/ufYnpi89XMW6nhfLAQNVG__DP2fTpewjbKgZ3I5n9II/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9OUV9OUF82/NTQ0NTItTUxNNDA5/Nzc2Nzc3NjNfMDMy/MDIwLUYtZ2VuZXJh/ZG9yLWVsZWN0cmlj/by1hLWdhc29saW5h/LTU1MDAtdy1wcmV0/dWwtMjYwMzUud2Vi/cA" alt="Card image cap">
      <div class="card-body">
        <p class="card-text">En esta sección usted podrá visualizar la tabla con los datos de los generadores registrados en el sistema</p>
        <a href="/generador/table" class="card-link">Ir a la sección</a>
      </div>
      <div class="card-footer border-top-blue-grey border-top-lighten-5 text-muted">
      </div>
    </div>
  </div>
  <div class="col-lg-4 col-md-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Apartado de Transacciones</h4>
        <h6 class="card-subtitle text-muted">Tabla de datos con posibilidad de modificación</h6>
      </div>
      <img class="" src="https://imgs.search.brave.com/QRxPUjR_b0ySmDAoO-BVINxzd9465CwPtiw_4aTbdLo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWcu/ZnJlZXBpay5jb20v/Zm90by1ncmF0aXMv/Z2VudGUtbmVnb2Np/b3MtZGFuZG9zZS1t/YW5vLWFjdWVyZG9f/NTM4NzYtMTE5Nzk2/LmpwZz9zaXplPTYy/NiZleHQ9anBn" alt="Card image cap">
      <div class="card-body">
        <p class="card-text">En esta sección usted podrá visualizar la lista actual de los datos de las transacciones registradas en el sistema</p>
        <a href="/transaccion/table" class="card-link">Ir a la sección</a>
        <div class="card-footer border-top-blue-grey border-top-lighten-5 text-muted">
        </div>
      </div>
    </div>
  </div>
</div>
  
{% endblock %}