front_practica_2/routes/route_generador.py
from .route_familia import *

router_generador = Blueprint('router_generador',__name__)

G_URL = f'{BASE_URL}/generador'

# TABLE GENERADOR ================================================================================

@router_generador.route('/generador/table')
def table_generador():
    response = requests.get(f'{G_URL}/all')
    attributes = requests.get(f'{G_URL}/attributes').json()['data']
    generadores = response.json()['data']
    for i in range(0,len(generadores)):
        generadores[i]['numero'] = i+1
    return render_template('generador/table_generador.html',generadores=generadores,attributes=attributes)


# BÚSQUEDA Y ORDENACIÓN ========================================================================

@router_familia.route('/generador/search/<attribute>/<value>')
def generador_search(attribute,value):
    response = requests.get(f'{G_URL}/search/{attribute}/{value}')
    attributes = requests.get(f'{G_URL}/attributes').json()['data']
    generadores = response.json()['data']
    for i in range(0,len(generadores)): 
        generadores[i]['numero'] = i+1
    return render_template('generador/table_generador.html',generadores=generadores,attributes=attributes)

@router_familia.route('/generador/sort/<attribute>/<orden>/<typesort>')
def generador_sort(attribute,orden,typesort):
    response = requests.get(f'{G_URL}/sort/{attribute}/{orden}/{typesort}')
    attributes = requests.get(f'{G_URL}/attributes').json()['data']
    generadores = response.json()['data']
    for i in range(0,len(generadores)): 
        generadores[i]['numero'] = i+1
    return render_template('generador/table_generador.html',generadores=generadores,attributes=attributes)

# SAVE GENERADOR =================================================================================

@router_generador.route('/generador/save')
def save_generador():
    return render_template('/generador/save_generador.html')
    
@router_generador.route('/generador/save/send',methods=['POST'])
def save_generador_send():
    data = request.form.to_dict()
    headers = {'Content-Type':'application/json'}
    response = requests.post(f'{G_URL}/save/',json=data,headers=headers)
    msg = response.json()
    key = ['info','info'] if response.status_code == 201 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
    return redirect('/generador/table')

# UPDATE GENERADOR ==============================================================================

@router_generador.route('/generador/update/<int:id>')
def update_generador(id):
    response = requests.get(f'{G_URL}/get/{id}')
    generador = response.json()['data']
    return render_template('generador/update_generador.html',generador=generador)

@router_generador.route('/generador/update/send',methods=['POST'])
def update_generador_send():
    json = request.form.to_dict()
    headers = {'Content-Type':'application/json'}
    response = requests.post(f'{G_URL}/update',json=json,headers=headers)
    msg = response.json()
    key = ['info','info'] if response.status_code == 200 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
    return redirect('/generador/table')

# DELETE GENERADOR =============================================================================

@router_generador.route('/generador/delete/<int:id>')
def delete_generador(id):
    response = requests.get(f'{G_URL}/get/{id}')
    generador = response.json()['data']
    return render_template('generador/delete_generador.html',generador=generador)

@router_generador.route('/generador/delete/send',methods=['POST'])
def delete_generador_send():
    response = requests.delete(f'{G_URL}/delete/{request.form['id']}')
    msg = response.json()
    key = ['info','info'] if response.status_code == 200 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
    return redirect('/generador/table')

front_practica_2/templates/generador/delete_generador.html
{% extends 'generador/generador_base.html' %}
{% block title %}Eliminar Generador{% endblock %}
{% block extra_routes %}
  <a href="#"> - </a><a href="/generador/delete/{{generador.id}}">Eliminar {{generador.id}}</a>
{% endblock %}
{% block content %}
<div class="card">
  <div class="card-header">
      <h4 class="card-title">Eliminar datos del Generador {{generador.id}}</h4>
  </div>

  <div class="card-block">
      <div class="card-body">
        <h3>¿Está seguro que quiere perder para siempre los siguientes datos?</h3>
        <div class="card-text">
          <ul>
            <li><strong>{{generador.modelo}}</strong></li>
            <li><strong>Precio: </strong>{{generador.precio}}</li>
            <li><strong>Consumo: </strong>{{generador.consumo}}</li>
            <li><strong>Potencia: </strong>{{generador.potencia}}</li>
          </ul> 
          <form action="/generador/delete/send" method="post">
            <input type="number" name="id" value="{{generador.id}}" readonly hidden>
            <a href="/generador/table">
              <button type="button" class="btn btn-success btn-min-width mr-1 mb-1"><i class="la la-chevron-left"></i>Volver</button>
            </a>
            <button type="submit" class="btn btn-danger btn-min-width mr-1 mb-1"><i class="la la-trash"></i>Eliminar</button>
          </form>
          </form>
        </div>         
      </div>
  </div>
</div>
  
{% endblock %}

front_practica_2/templates/generador/generador_base.html
{% extends 'base.html' %}
{% block main_menu_content %}
<div class="main-menu-content">
  <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
    <li class="nav-item"><a href="/"><i class="ft-home"></i><span class="menu-title"
          data-i18n="">Inicio</span></a>
    </li>
    <li class="nav-item"><a href="/familia/table"><i class="la la-group"></i><span class="menu-title"
          data-i18n="">Familias</span></a>
    </li>
    <li class="active"><a href="/generador/table"><i class="la la-lightbulb-o"></i><span class="menu-title"
      data-i18n="">Generadores</span></a>
    </li>
    <li class="nav-item"><a href="/transaccion/table"><i class="la la-exchange"></i><span class="menu-title"
      data-i18n="">Transacciones</span></a>
    </li>
    <li class="nav-item"><a href="/historial/table"><i class="la la-history"></i><span class="menu-title"
      data-i18n="">Historial Acciones</span></a>
    </li>
  </ul>
</div>
<div class="navigation-background"></div>
</div>
{% endblock %}

{% block app_content %}
<div class="app-content content">
  <div class="content-wrapper">
    <div class="content-wrapper-before"></div>
    <div class="content-header row">
      <div class="content-header-left col-md-4 col-12 mb-2">
        <h3 class="content-header-title">GENERADORES</h3>
      </div>
      <div class="content-header-right col-md-8 col-12">
        <div class="breadcrumbs-top float-md-right">
          <div class="breadcrumb-wrapper mr-1">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="/">Home</a><a href="#"> - </a><a href="/generador/table">Generadores</a>{% block extra_routes %}
                {% endblock %}
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

front_practica_2/templates/generador/save_generador.html
{% extends 'generador/generador_base.html' %}
{% block title %}Guardar Generador{% endblock %}
{% block extra_routes %}
  <a href="#"> - </a><a href="/generador/save">Guardar</a>
{% endblock %}
{% block content %}
<div class="card">
  <div class="card-header">
    <h4 class="card-title">GUARDAR GENERADOR</h4>
  </div>
  <div class="card-block">
    <div class="card-body">

      <a href="/generador/table">
        <button type="button" class="btn btn-icon btn-danger mr-1">
          <i class="la la-arrow-left"></i> <strong>Tabla de Generadores</strong>
        </button>
      </a>

      <form action="/generador/save/send" method="post">
        
        <h5 class="mt-2"><label for="modelo">Modelo</label></h5>
        <fieldset class="form-group">
            <input required type="text" class="form-control" id="modelo" name="modelo" >
        </fieldset>
        
        <h5 class="mt-2"><label for="precio">Precio</label></h5>
        <fieldset class="form-group">
            <input required type="number" step="0.01" class="form-control" id="precio" name="precio" min="100">
        </fieldset>

        <h5 class="mt-2"><label for="consumo">Consumo</label></h5>
        <fieldset class="form-group">
            <input required type="number" step="0.01" class="form-control" id="consumo" name="consumo" min="100">
        </fieldset>

        <h5 class="mt-2"><label for="potencia">Potencia</label></h5>
        <fieldset class="form-group">
            <input required type="number" step="0.01" class="form-control" id="potencia" name="potencia" min="100">
        </fieldset>

        <button type="submit" class="btn mb-1 btn-primary btn-lg btn-block">Guardar Generador</button>
      </form>

    </div>
  </div>
</div>
{% endblock %}

front_practica_2/templates/generador/table_generador.html
{% extends 'generador/generador_base.html' %}
{% block title %}Tabla de Generadoress{% endblock %}
{% block static_content %}
  <link rel="stylesheet" href="{{ url_for('static',filename='assets/css/search.css') }}">
{% endblock %}
{% block content %}
<div class="card">
  <div class="card-header">
      <h4 class="card-title">Generadores Registrados</h4>
  </div>
    {% with messages = get_flashed_messages(with_categories=True)  %}
      {% if messages %}
        {% for message in messages %}
          {% if message[0] == 'info' %}
          <p class="card-subtitle" style="color:#11fc2d"> <i class="la la-check-circle-o"></i> {{ message[1] }}</p>
          {% else %}     
            <p class="card-subtitle" style="color: #fc1111;"> <i class="la la-remove"></i> {{ message[1] }}</p>
          {% endif %}               
        {% endfor %}         
      {% endif %}
    {% endwith %}
  <div class="card-block">
      <div class="card-body">
        <a href="/generador/save">
          <button type="button" class="btn btn-dark btn-min-width mr-1 mb-1">
            <i class="la la-plus"></i>
          </button>
        </a>

          <a id="searchRequest" href="/generador/table" hidden></a>
          <a id="sortRequest" href="/generador/table" hidden></a>
        

          <div class="btn-group mr-1 mb-1">
            <button type="button" class="btn btn-info" onclick="searchUtility('generador')"><i class="la la-search"></i></button>
            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            </button>
            <div class="dropdown-menu">
                {% for attribute in attributes %}
                  <p class="p-option" value="{{ attribute }}" onclick="buildSearchUrl('generador','{{ attribute }}')">{{ attribute }}</p>
                {% endfor %}
            </div>
          </div>
          <input type="text" id="inputS"><br>

          <div class="btn-group mr-1 mb-1">
              <button type="button" class="btn btn-info" onclick="sortUtility('generador','1')"><i class="la la-sort-amount-asc"></i></button>
              <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              </button>
              <div class="dropdown-menu">
                  {% for attribute in attributes %}
                    <p class="p-option" value="{{ attribute }}" onclick="buildSortUrl('generador','{{ attribute }}')">{{ attribute }}</p>
                  {% endfor %}
              </div>
          </div>

          <div class="btn-group mr-1 mb-1">
            <button type="button" class="btn btn-info" onclick="sortUtility('generador','0')"><i class="la la-sort-amount-desc"></i></button>
            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            </button>
            <div class="dropdown-menu">
                {% for attribute in attributes %}
                  <p class="p-option" value="{{ attribute }}" onclick="buildSortUrl('generador','{{ attribute }}')">{{ attribute }}</p>
                {% endfor %}
            </div>
        </div>

        <select name="selection" id="inputSrt">
          <option value="0" onclick="tipeSort('0')">QUICK_SORT</option>
          <option value="1" onclick="tipeSort('1')">MERGE_SORT</option>
          <option value="2" onclick="tipeSort('2')">SHELL_SORT</option>
        </select>
        
        <table class="table">
          <thead class="thead-dark">
            <th>Nro</th>
            <th>Modelo</th>
            <th>Precio</th>
            <th>Consumo</th>
            <th>Potencia</th>
            <th>Acción</th>
          </thead>
          <tbody>
            {% for generador in generadores %}
              <tr>
                <td>{{ generador.numero }}</td>
                <td>{{ generador.modelo }}</td>
                <td>${{ generador.precio }}</td>
                <td>{{ generador.consumo }} L</td>
                <td>{{ generador.potencia }} W</td>
                <td>
                  <a href="{{ url_for('router_generador.update_generador',id=generador.id) }}" ><i class="la la-pencil"></i></a>
                  <a href="{{ url_for('router_generador.delete_generador',id=generador.id) }}" ><i class="la la-trash"></i></a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>      
      </div>
  </div>
</div>

<script src="{{ url_for('static',filename='js/sortSearchScript.js') }}"></script>

{% endblock %}

front_practica_2/templates/generador/update_generador.html
{% extends 'generador/generador_base.html' %}
{% block title %}Actualizar datos del Generador{% endblock %}
{% block extra_routes %}
  <a href="#"> - </a><a href="/update/generador/{{generador.id}}">Editar {{generador.id}}</a>
{% endblock %}
{% block content %}
<div class="card">
  <div class="card-header">
    <h4 class="card-title">ACTUALIZAR GENERADOR</h4>
  </div>
  <div class="card-block">
    <div class="card-body">

      <a href="/generador/table">
        <button type="button" class="btn btn-icon btn-danger mr-1">
          <i class="la la-arrow-left"></i> <strong>Volver</strong>
        </button>
      </a>

      <form action="/generador/update/send" method="post">
        <input hidden type="number" value="{{generador.id}}" name="id">

        <h5 class="mt-2"><label for="modelo">Modelo</label></h5>
        <fieldset class="form-group">
            <input required type="text" class="form-control" id="modelo" name="modelo" value="{{generador.modelo}}" min="100">
        </fieldset>
        
        <h5 class="mt-2"><label for="precio">Precio</label></h5>
        <fieldset class="form-group">
            <input required type="number" step="0.01" class="form-control" id="precio" name="precio" value="{{generador.precio}}" min="100">
        </fieldset>

        <h5 class="mt-2"><label for="consumo">Consumo</label></h5>
        <fieldset class="form-group">
            <input required type="number" step="0.01" class="form-control" id="consumo" name="consumo" value="{{generador.consumo}}" min="100">
        </fieldset>

        <h5 class="mt-2"><label for="potencia">potencia</label></h5>
        <fieldset class="form-group">
            <input required type="number" step="0.01" class="form-control" id="potencia" name="potencia" value="{{generador.potencia}}" min="100">
        </fieldset>

        <button type="submit" class="btn mb-1 btn-primary btn-lg btn-block">Actualizar Generador</button>
      </form>

    </div>
  </div>
</div>
  
{% endblock %}