front_practica_2/routes/route_familia.py
from flask import Blueprint, redirect, render_template, request, flash
import requests

router_familia = Blueprint('router_familia',__name__)

@router_familia.route('/')
def home():
    return render_template('index.html')

BASE_URL = 'http://localhost:8080/api'

F_URL = f'{BASE_URL}/familia'

# TABLE FAMILIA =============================================================================================

@router_familia.route('/familia/table')
def table_familia():
    response = requests.get(f'{F_URL}/all')
    attributes = requests.get(f'{F_URL}/attributes').json()['data']
    familias = response.json()['data']
    for i in range(0,len(familias)): 
        familias[i]['numero'] = i+1
    return render_template('familia/table_familia.html',familias=familias,attributes=attributes)


# BÚSQUEDA Y ORDENACIÓN ====================================================================================

@router_familia.route('/familia/search/<attribute>/<value>')
def search(attribute,value):
    response = requests.get(f'{F_URL}/search/{attribute}/{value}')
    attributes = requests.get(f'{F_URL}/attributes').json()['data']
    familias = response.json()['data']
    for i in range(0,len(familias)): 
        familias[i]['numero'] = i+1
    return render_template('familia/table_familia.html',familias=familias,attributes=attributes)

@router_familia.route('/familia/sort/<attribute>/<orden>/<typesort>')
def sort(attribute,orden,typesort):
    response = requests.get(f'{F_URL}/sort/{attribute}/{orden}/{typesort}')
    attributes = requests.get(f'{F_URL}/attributes').json()['data']
    familias = response.json()['data']
    for i in range(0,len(familias)): 
        familias[i]['numero'] = i+1
    return render_template('familia/table_familia.html',familias=familias,attributes=attributes)


# SAVE FAMILIA ============================================================================================

@router_familia.route('/familia/save')
def save_familia():
    response = requests.get(f'{F_URL}/enumerations')
    return render_template('familia/save_familia.html',enumeracion=response.json()['data'])

@router_familia.route('/familia/save/send', methods=['POST'])
def save_familia_send():
    headers = {'Content-Type':'application/json'}
    data = request.form.to_dict()
    response = requests.post(f'{F_URL}/save',json=data,headers=headers)
    msg = response.json()
    key = ['info','info'] if response.status_code == 201 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
    return redirect('/familia/table')
    
# FAMILIA UPDATE ========================================================================

@router_familia.route('/familia/update/<int:id>')
def update_familia(id):
    response = requests.get(f'{F_URL}/get/{id}')
    familia = response.json()['data']
    response = requests.get(f'{F_URL}/enumerations')
    print(response)
    enums = response.json()['data']
    
    return render_template('familia/update_familia.html',context={"familia": familia, "enums" : enums})

@router_familia.route('/familia/update/send',methods=['POST'])
def update_familia_send():
    data = request.form.to_dict()
    headers = {'Content-Type':'application/json'}
    response = requests.post(f'{F_URL}/update',json=data,headers=headers)
    msg = response.json()
    key = ['info','info'] if response.status_code == 200 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
        
    return redirect('/familia/table')

# DELETE FAMILIA ========================================================================

@router_familia.route('/delete/familia/<int:id>')
def delete_familia(id):
    response = requests.get(f'{F_URL}/get/{id}')
    familia = response.json()['data']
    return render_template('familia/delete_familia.html',familia=familia)

@router_familia.route('/delete/familia/send',methods=['POST'])
def delete_familia_send():
    response = requests.delete(f'{F_URL}/delete/{request.form['id']}')
    msg = response.json()
    key = ['info','info'] if response.status_code == 200 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
    return redirect('/familia/table')



# HISTORIAL DE ACCIONES ==============================================================================

H_URL = f'{BASE_URL}/historial'

@router_familia.route('/historial/table')
def table_historial():
    acciones = requests.get(f'{H_URL}/all').json()['data']
    attributes = requests.get(f'{H_URL}/attributes').json()['data']
    for i in range(0,len(acciones)):
        acciones[i]['numero'] = i+1
    return render_template('historial/table_historial.html',acciones=acciones,attributes=attributes)

# DELETE ACCION =================================================================================

@router_familia.route('/historial/delete/<id>')
def delete_historial(id):
    accion = requests.get(f'{H_URL}/get/{id}').json()['data']
    print(accion)
    return render_template('historial/delete_historial.html',accion=accion)

@router_familia.route('/historial/delete/send/<id>')
def delete_historial_send(id):
    response = requests.delete(f'{H_URL}/delete/{id}')
    msg = response.json()
    key = ['info','info'] if response.status_code == 200 else ['data','error']
    flash(f'{msg['status']}: {msg[key[0]]}',category=key[1])
    return redirect('/historial/table')

# BUSQUEDA Y ORDENACIÓN =================================================================

@router_familia.route('/historial/search/<attribute>/<value>')
def historial_search(attribute,value):
    response = requests.get(f'{H_URL}/search/{attribute}/{value}')
    attributes = requests.get(f'{H_URL}/attributes').json()['data']
    acciones = response.json()['data']
    for i in range(0,len(acciones)): 
        acciones[i]['numero'] = i+1
    return render_template('historial/table_historial.html',acciones=acciones,attributes=attributes)

@router_familia.route('/historial/sort/<attribute>/<orden>/<typesort>')
def historial_sort(attribute,orden,typesort):
    response = requests.get(f'{H_URL}/sort/{attribute}/{orden}/{typesort}')
    attributes = requests.get(f'{H_URL}/attributes').json()['data']
    acciones = response.json()['data']
    for i in range(0,len(acciones)): 
        acciones[i]['numero'] = i+1
    return render_template('historial/table_historial.html',acciones=acciones,attributes=attributes)


# Ay! bendita sea mi mama
# por haberme parido macho!
# Aaay, mama!

#🗣️🗣️🗣️🗣️🗣️🗣️🗣️

front_practica_2/templates/familia/delete_familia.html
{% extends 'familia/familia_base.html' %}
{% block title %}Borrar datos de la Familia{% endblock %}
{% block extra_rutes %}
  <a href="#"> - </a><a href="/familia/delete/{{familia.id}}">Eliminar {{familia.codigoFamilia}}</a>
{% endblock %}
{% block content %}
<div class="card">
  <div class="card-header">
      <h4 class="card-title">Eliminar datos de la Familia {{familia.codigoFamilia}}</h4>
  </div>

  <div class="card-block">
      <div class="card-body">
        <h3>¿Está seguro que quiere perder para siempre los siguientes datos?</h3>
        <div class="card-text">
          <ul>
            <li><strong>Familia {{familia.apellidosRepresentantes}}</strong></li>
            <li><strong>Número de integrantes: </strong>{{familia.nroIntegrantes}}</li>
            <li><strong>Ingresos mensuales: </strong>{{familia.ingresosMensuales}}</li>
            <li><strong>Cantón: </strong>{{familia.canton}}</li>
            <li><strong>Nivel socioeconómico: </strong>{{familia.nivelSocioeconomico}}</li>
          </ul> 
          <form action="/delete/familia/send" method="post">
            <input type="number" name="id" value="{{familia.id}}" readonly hidden>
            <a href="/familia/table">
              <button type="button" class="btn btn-success btn-min-width mr-1 mb-1"><i class="la la-chevron-left"></i>Volver</button>
            </a>
            <button type="submit" class="btn btn-danger btn-min-width mr-1 mb-1"><i class="la la-trash"></i>Eliminar</button>
          </form>
        </div>         
      </div>
  </div>
</div>
{% endblock %}

front_practica_2/templates/familia/familia_base.html
{% extends 'base.html' %}

{% block main_menu_content %}
  <div class="main-menu-content">
    <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
      <li class="nav-item"><a href="/"><i class="ft-home"></i><span class="menu-title"
            data-i18n="">Inicio</span></a>
      </li>
      <li class="active"><a href="/familia/table"><i class="la la-group"></i><span class="menu-title"
            data-i18n="">Familias</span></a>
      </li>
      <li class="nav-item"><a href="/generador/table"><i class="la la-lightbulb-o"></i><span class="menu-title"
        data-i18n="">Generadores</span></a>
      </li>
      <li class="nav-item"><a href="/transaccion/table"><i class="la la-exchange"></i><span class="menu-title"
        data-i18n="">Transacciones</span></a>
      </li>
      <li class="nav-item"><a href="/historial/table"><i class="la la-history"></i><span class="menu-title"
        data-i18n="">Historial Acciones</span></a>
      </li>
    </ul>
  </div>
  <div class="navigation-background"></div>
  </div>
{% endblock %}

{% block app_content %}
<div class="app-content content">
  <div class="content-wrapper">
    <div class="content-wrapper-before"></div>
    <div class="content-header row">
      <div class="content-header-left col-md-4 col-12 mb-2">
        <h3 class="content-header-title">FAMILIAS</h3>
      </div>
      <div class="content-header-right col-md-8 col-12">
        <div class="breadcrumbs-top float-md-right">
          <div class="breadcrumb-wrapper mr-1">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="/">Home</a><a href="#"> - </a>
                <a href="/familia/table">Familias</a> {% block extra_rutes %}{% endblock %}
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

front_practica_2/templates/familia/save_familia.html
{% extends 'familia/familia_base.html' %}
{% block title %}Guardar Familia{% endblock %}
{% block extra_rutes %}
  <a href="#"> - </a><a href="/familia/save">Guardar</a>
{% endblock %}
{% block content %}
<div class="card">
  <div class="card-header">
    <h4 class="card-title">GUARDAR FAMILIA</h4>
  </div>
  <div class="card-block">
    <div class="card-body">
      <a href="/familia/table">
        <button type="button" class="btn btn-icon btn-danger mr-1">
          <i class="la la-arrow-left"></i> <strong>Tabla de Familias</strong>
        </button>
      </a>
      
      <form action="/familia/save/send" method="post">

        <h5 class="mt-2"><label for="codigoFamilia">Código único de Familia</label></h5>
        <fieldset class="form-group">
            <input required type="text" class="form-control" id="codigoFamilia" name="codigoFamilia" placeholder="ej. F0034" >
        </fieldset>

        <h5 class="mt-2"><label for="numeroIntegrantes">Numero de Integrantes</label></h5>
        <fieldset class="form-group">
            <input required min="0" max="60" type="number" class="form-control" id="numeroIntegrantes" name="nroIntegrantes" >
        </fieldset>

        <h5 class="mt-2"><label for="apellidosRepresentantes">Apellidos de los representantes de la familia</label></h5>
        <fieldset class="form-group">
            <input required type="text" class="form-control" id="apellidosRepresentantes" name="apellidosRepresentantes" >
        </fieldset>
        
        <h5 class="mt-2"><label for="ingresosMensuales">Ingresos Mensuales</label></h5>
        <fieldset class="form-group">
            <input required min="10" type="number" step="0.01" class="form-control" id="ingresosMensuales" name="ingresosMensuales">
        </fieldset>

        <label for="canton"><h5 class="mt-2">Canton</h5></label>
        <fieldset class="form-group">
          <select required class="form-control" id="canton" name="canton">
            {% for canton in enumeracion.cantones %}
              <option value="{{canton}}">{{canton}}</option>
            {% endfor %}
          </select>
        </fieldset>

        {#- 
          Esta parte se omite porque el backend calcula automáticamente el nivel socioeconomico
        <label for="nivelSocioeconomico"><h5 class="mt-2">Nivel Socioeconomico</h5></label>        
        <fieldset class="form-group">
          <select required class="form-control" id="nivelSocioeconomico" name="nivelSocioeconomico">
            {% for nivel in enumeracion.niveles %}
              <option value="{{nivel}}">{{nivel}}</option>
            {% endfor %}
          </select>
        </fieldset>
        -#}

        <button type="submit" class="btn mb-1 btn-primary btn-lg btn-block">Guardar Familia </button>
      </form>

    </div>
  </div>
</div>
{% endblock %}

front_practica_2/templates/familia/table_familia.html
{% extends 'familia/familia_base.html' %}
{% block title %}Tabla de Familias{% endblock %}

{% block static_content %}
  <link rel="stylesheet" href="{{ url_for('static',filename='assets/css/search.css') }}">
{% endblock %}

{% block content %}

<div class="card">
  <div class="card-header">
      <h4 class="card-title">Familias Registradas</h4>
  </div>
    {% with messages = get_flashed_messages(with_categories=True)  %}
      {% if messages %}
        {% for message in messages %}
          {% if message[0] == 'info' %}
            <p class="card-subtitle" style="color:#11fc2d"> <i class="la la-check-circle-o"></i> {{ message[1] }}</p>
          {% else %}     
            <p class="card-subtitle" style="color: #fc1111;"> <i class="la la-remove"></i> {{ message[1] }}</p>
          {% endif %}               
        {% endfor %}         
      {% endif %}
    {% endwith %}
  <div class="card-block">
      <div class="card-body">
        <a href="/familia/save">
          <button type="button" class="btn btn-dark btn-min-width mr-1 mb-1">
            <i class="la la-plus"></i>
          </button>
        </a>
        <a id="searchRequest" href="/familia/table" hidden></a>
        <a id="sortRequest" href="/familia/table" hidden></a>
        

        <div class="btn-group mr-1 mb-1">
          <button type="button" class="btn btn-info" onclick="searchUtility('familia')"><i class="la la-search"></i></button>
          <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          </button>
          <div class="dropdown-menu">
              {% for attribute in attributes %}
                <p class="p-option" value="{{ attribute }}" onclick="buildSearchUrl('familia','{{ attribute }}')">{{ attribute }}</p>
              {% endfor %}
          </div>
      </div>
      <input type="text" id="inputS"><br>

      <div class="btn-group mr-1 mb-1">
        <button type="button" class="btn btn-info" onclick="sortUtility('familia','1')"><i class="la la-sort-amount-asc"></i></button>
        <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        </button>
        <div class="dropdown-menu">
            {% for attribute in attributes %}
              <p class="p-option" value="{{ attribute }}" onclick="buildSortUrl('familia','{{ attribute }}')">{{ attribute }}</p>
            {% endfor %}
        </div>
    </div>

    <div class="btn-group mr-1 mb-1">
      <button type="button" class="btn btn-info" onclick="sortUtility('familia','0')"><i class="la la-sort-amount-desc"></i></button>
      <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      </button>
      <div class="dropdown-menu">
          {% for attribute in attributes %}
            <p class="p-option" value="{{ attribute }}" onclick="buildSortUrl('familia','{{ attribute }}')">{{ attribute }}</p>
          {% endfor %}
      </div>
  </div>

  <select name="selection" id="inputSrt">
    <option value="0" onclick="tipeSort('0')">QUICK_SORT</option>
    <option value="1" onclick="tipeSort('1')">MERGE_SORT</option>
    <option value="2" onclick="tipeSort('2')">SHELL_SORT</option>
  </select>
      
        
        <table class="table">
          <thead class="thead-dark">
            <th>Nro</th>
            <th>Código Familia</th>
            <th>Apellidos familia</th>
            <th>Nro Integrantes</th>
            <th>Canton</th>
            <th>Ingresos Mensuales</th>
            <th>Nvl Socioeconomico</th>
            <th>Acción</th>
          </thead>
          <tbody>
            {% for familia in familias %}
              <tr>
                <td>{{ familia.numero }}</td>
                <td>{{ familia.codigoFamilia }}</td>
                <td>{{ familia.apellidosRepresentantes }}</td>
                <td>{{ familia.nroIntegrantes }}</td>
                <td>{{ familia.canton }}</td>
                <td>{{ familia.ingresosMensuales }}</td>
                <td>{{ familia.nivelSocioeconomico }}</td>
                <td>
                  <a href="{{ url_for('router_familia.update_familia',id=familia.id) }}"><i class="la la-pencil"></i></a>
                  <a href="{{ url_for('router_familia.delete_familia',id=familia.id ) }}"><i class="la la-trash"></i></a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>      
      </div>
  </div>
</div>

<script src="{{ url_for('static',filename='js/sortSearchScript.js') }}"></script>


{% endblock %}

front_practica_2/templates/familia/update_familia.html
{% extends 'familia/familia_base.html' %}
{% block title %}Modificar Familia{% endblock %}
{% block extra_rutes %}
  <a href="#"> - </a><a href="/familia/update/{{context.familia.id}}">Editar {{context.familia.id}}</a>
{% endblock %}
{% block content %}
<div class="card">
  <div class="card-header">
    <h4 class="card-title">Editar familia</h4>
  </div>
  <div class="card-block">
    <div class="card-body">

      <a href="/familia/table">
        <button type="button" class="btn btn-icon btn-danger mr-1">
          <i class="la la-arrow-left"></i> <strong>Volver</strong>
        </button>
      </a>

      <form action="/familia/update/send" method="post">
        <input type="number" value="{{context.familia.id}}" name="id" id="id" readonly hidden>

        <h5 class="mt-2"><label for="codigoFamilia">Código único de Familia</label></h5>
        <fieldset class="form-group">
            <input required type="text" class="form-control" id="codigoFamilia" name="codigoFamilia" value="{{ context.familia.codigoFamilia }}" >
        </fieldset>


        <h5 class="mt-2"><label for="numeroIntegrantes">Numero de Integrantes</label></h5>
        <fieldset class="form-group">
            <input type="number" class="form-control" id="numeroIntegrantes" 
            name="nroIntegrantes" value="{{context.familia.nroIntegrantes}}" >
        </fieldset>

        <h5 class="mt-2"><label for="apellidosRepresentantes">Apellidos de los representantes</label></h5>
        <fieldset class="form-group">
            <input type="text" class="form-control" id="apellidosRepresentantes" 
            name="apellidosRepresentantes" value="{{context.familia.apellidosRepresentantes}}" >
        </fieldset>
        
        <h5 class="mt-2"><label for="ingresosMensuales">Ingresos Mensuales</label></h5>
        <fieldset class="form-group">
            <input type="number" step="0.01" class="form-control" id="ingresosMensuales" 
            name="ingresosMensuales" value="{{context.familia.ingresosMensuales}}">
        </fieldset>

        <label for="canton"><h5 class="mt-2">Canton</h5></label>
        <fieldset class="form-group">
          <select class="form-control" id="canton" name="canton">
            {% for canton in context.enums.cantones %}

              <option value="{{canton}}"
                {% if canton == context.familia.canton %}
                  selected
                {% endif %}
              >{{canton}}</option>
            {% endfor %}
          </select>
        </fieldset>

        <button type="submit" class="btn mb-1 btn-primary btn-lg btn-block">Guardar Familia</button>
      </form>

    </div>
  </div>
</div>
{% endblock %}